### PR TITLE
TA-1_Defined the Git WorkFlow for future development strategy.

### PR DESCRIPTION
**Pull request by AdrianaUserName**
As part of this Pull Request, the definition of GIT workflow was added. Please review and let me know if all is good and I can merge it.

### CODE REVIEW

**Review by TestAutomationPanfilElena — APPROVED** [review]

**Review by TestAutomationPanfilElena — APPROVED** [review]

**Review by MarianaLearningAccount — APPROVED** [review]

**Review by PascariPetru — CHANGES_REQUESTED** [review]
Hi Adriana, please add missing steps according to slide 27 from power point presentation
image

**Comment by AdrianaUserName** [comment]
> Hi Adriana, please add missing steps according to slide 27 from power point presentation image

Hello , I have executed the changes you mentioned , can you please accept my Pull Request. Thanks!

**Comment by AdrianaUserName** [comment]
@PascariPetru I executed the changes , can you please approve now. Thanks a lot.

**Review by PascariPetru — APPROVED** [review]
Perfect!

**Pull request merged**
